//
//  main.swift
//  Pentagon Numbers
//
//  Created by Vincent Snow on 1/13/21.
//
/*Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
 
 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

 It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

 Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
 */

import Foundation

var pentDict: [Int:Int] = [:]
let start = Date()
for i in 1...10000 {
    let pent = (i * ((3 * i) - 1)) / 2
    pentDict[pent] = 1
}

outerloop: for i in pentDict {
    for j in pentDict {
        if pentDict[i.key+j.key] == 1 && pentDict[i.key-j.key] == 1 {
            print(i.key, j.key, i.key+j.key, i.key-j.key)
            break outerloop
        }
    }
}

print(Date().timeIntervalSince(start))
